# ---- SRP: Default = Disallowed, allow Windows & Program Files paths ----
- name: Enable SRP - Default Disallowed
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers
    name: DefaultLevel
    data: 0x00040000
    type: dword

- name: SRP Policy Level (Transparent Enabled)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers
    name: PolicyScope
    data: 0     # All users except local admins
    type: dword

- name: SRP allow Windows folder
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{WIN}
    state: present

- name: SRP allow Windows folder rule
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{WIN}
    name: ItemData
    data: "%WINDIR%\\*"
    type: string

- name: SRP Windows folder security level
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{WIN}
    name: SaferFlags
    data: 0
    type: dword

- name: SRP allow Program Files
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF}
    state: present

- name: SRP allow Program Files rule
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF}
    name: ItemData
    data: "%PROGRAMFILES%\\*"
    type: string

- name: SRP Program Files security level
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF}
    name: SaferFlags
    data: 0
    type: dword

# Optionally allow Program Files (x86)
- name: SRP allow Program Files (x86)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF86}
    state: present

- name: SRP allow Program Files (x86) rule
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF86}
    name: ItemData
    data: "%PROGRAMFILES(x86)%\\*"
    type: string

- name: SRP Program Files (x86) security level
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{PF86}
    name: SaferFlags
    data: 0
    type: dword

# ---- UAC: Highest level ----
- name: Elevate UAC to Always Notify
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: ConsentPromptBehaviorUser
    data: 1
    type: dword

- name: Require secure desktop for elevation
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: PromptOnSecureDesktop
    data: 1
    type: dword

# ---- SmartScreen (Windows & Edge) ----
- name: Enable Windows Defender SmartScreen (System)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: EnableSmartScreen
    data: 1
    type: dword

- name: Set SmartScreen level to Warn
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: ShellSmartScreenLevel
    data: Warn
    type: string

- name: Edge SmartScreen
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Edge
    name: SmartScreenEnabled
    data: 1
    type: dword

# ---- Hide key Security/Settings pages for standard users (optional hardening) ----
- name: Hide Windows Security app (standard users)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Notifications
    name: DisableEnhancedNotifications
    data: 1
    type: dword