# Configure Windows Update policy: Auto install every day at 03:00
- name: Enable automatic updates
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 0
    type: dword

- name: Set AUOptions = 4 (Auto download & schedule install)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: AUOptions
    data: 4
    type: dword

- name: Schedule daily install time 03:00
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: ScheduledInstallTime
    data: 3
    type: dword

- name: Force detection now (one-off)
  ansible.windows.win_shell: "UsoClient StartScan; UsoClient StartDownload; UsoClient StartInstall"
  changed_when: false
  failed_when: false